---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-on-defaultns
  #namespace: default
  labels:
    app: nginx-deployment-on-defaultns
spec:
  ports:
  # port=available to other containers
  - port: 8080
    name: http
    # targetPort=exposed from inside container
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-deployment-on-defaultns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-dep-cm-on-defaultns
  #namespace: default
data:
  config.indexhtml: |
    <h1>This is index.html from a nginx-deployment-on-defaultns</h1>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-on-defaultns
  #namespace: default
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment-on-defaultns
  template:
    metadata:
      labels:
        app: nginx-deployment-on-defaultns
        version: v1
      # avoid istio envy project if being auto-injected
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      volumes:
      - name: nginx-dep-homedir
        projected:
          sources:
          - configMap:
              name: nginx-dep-cm-on-defaultns
              items:
                 - key: config.indexhtml
                   path: index.html
      containers:
      - name: nginx
        image: nginx:1.19
        volumeMounts:
        - name: nginx-dep-homedir
          mountPath: "/usr/share/nginx/html"
          readOnly: true
        ports:
        - containerPort: 80
