#
# this is NOT used by ansible, it is only used to aggregate values for my blog article
# The ansible role uses the templates
#
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-hello-world-web-service
  #namespace: default
  annotations:
    # https://github.com/ubuntu/microk8s/issues/2035
    kubernetes.io/ingress.class: public # was 'nginx' before microk8s 1.20
spec:
  tls:
  - hosts: [ "microk8s.local" ]
    # secret must be in same namespace
    secretName: tls-credential
  rules:

  - host: microk8s.local
    http:
      paths:
      - pathType: Prefix #Exact
        path: "/myhello/"
        backend:
          service:
            name: golang-hello-world-web-service
            port:
              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-hello-world-web-service2
  #namespace: default
  annotations:
    # mathes ingress-class argument coming from:
    #   roles/add_secondary_ingress/templates/nginx-ingress-secondary-microk8s-controller.yaml.j2
    kubernetes.io/ingress.class: secondary
spec:
  tls:
  - hosts:
    -  microk8s-secondary.local
    # secret must be in same namespace
    secretName: tls-secondary-credential
  rules:

  - host: microk8s-secondary.local
    http:
      paths:
      - pathType: Prefix #Exact
        path: "/myhello2/"
        backend:
          service:
            name: golang-hello-world-web-service2
            port:
              number: 8080

