---

- hosts: microk8s
  gather_facts: yes
  become: yes

  vars:

  roles:
    - role: nginx-exposed
    - role: nginx-ingress

    #- role: istio-operator
    #- role: istio-gateway
    #- role: hello-app-with-nginx-ingress
