---

- hosts: microk8s
  gather_facts: yes
  become: yes

  vars:
    # version needed by more than one role (namespace labels)
    istio_version: 1.7.5
    istio_ingress_tested_from_localhost: true

  roles:
    #- additional-netplan-ip
    #- microk8s-prereq
    #- ansible_role_microk8s
    #- microk8s-get-kubeconfig
    #- k9s
    #- kubectl-proxy
    #- kubernetes-dashboard-rbac

    #- cert-with-ca
    #- reapply-tls-secrets

    #- nginx-ingress

    - istio-operator
    - istio-gateway
    #- hello-app-with-nginx-ingress
