---

- hosts: microk8s
  gather_facts: yes
  become: yes

  # most vars are coming from 'group_vars/' directory
  vars:
    # version needed by more than one role (namespace labels)
    istio_version: 1.9.7
    istio_ingress_tested_from_localhost: true

  # these roles only need to be applied to first node in cluster
  roles:
    - wait-for-microk8s

    # assign MetalLB the use of the additional NIC on microk8s-1
    - metallb-service

    # istio operator (istio-operator) and primary+secondary ingress gateway services (istio-system)
    - istio-operator
    # istio gateways (default)
    - istio-gateway

    # deploys hello world to primary and secondary
    - istio-helloworld

