---
# ansible-playbook playbook_microk8s.yml

- hosts: microk8s_HA
  gather_facts: yes
  become: yes

  vars:
    # set to true if more than one host in microk8s_HA group
    microk8s_enable_HA: false

  roles:
    - role: microk8s-prereq
    - role: ansible_role_microk8s
    - role: cert-with-ca
    - role: k9s

    #- role: microk8s-get-kubeconfig
    #- role: kubectl-proxy
    #- role: kubernetes-dashboard-rbac
    #- role: additional-netplan-ip
    #- role: reapply-tls-secrets
    #- role: nginx-ingress

    #- role: istio-operator
    #- role: istio-gateway
    #- role: hello-app-with-nginx-ingress
