---

- hosts: microk8s
  gather_facts: yes
  become: yes

  vars:

  roles:
    - role: golang-hello-world-web

    # google sample hello app on nginx ingress
    #- role: hello-app-with-nginx-ingress
