---

- hosts: microk8s
  gather_facts: yes
  become: yes

  vars:
    istio_version: 1.7.5

  roles:
    # I don't believe this is necessary at all, already supplied with microk8s ingress
    #- role: nginx-ingress

    - role: nginx-exposed
    #- role: hello-app-with-nginx-ingress

    #- role: istio-operator
    #- role: istio-gateway
