---

# deploy microk8s
- hosts: microk8s_HA
  gather_facts: yes
  become: yes
  vars:
    microk8s_enable_HA: true

  roles:
    - microk8s-prereq
    - ansible_role_microk8s
    - k9s

# fetch kubeconfig locally for convenience
- hosts: microk8s
  gather_facts: no
  become: yes
  roles:
    - microk8s-get-kubeconfig-local
