---

- hosts: microk8s
  gather_facts: yes
  become: yes

  vars:
    # version needed by more than one role (namespace labels)
    istio_version: 1.7.5
    istio_ingress_tested_from_localhost: true

  roles:
    #- role: additional-netplan-ip
    #- role: microk8s-prereq
    #- role: ansible_role_microk8s
    #- role: microk8s-get-kubeconfig
    #- role: k9s
    #- role: kubectl-proxy
    #- role: kubernetes-dashboard-rbac

    #- role: cert-with-ca
    #- role: reapply-tls-secrets

    #- role: nginx-ingress

    - role: istio-operator
    - role: istio-gateway
    #- role: hello-app-with-nginx-ingress
