---
# ansible-playbook playbook_microk8s.yml

- hosts: microk8s
  gather_facts: yes
  become: yes

  vars:
    microk8s_version: "1.20/stable"
    # on Ubuntu focal, throws error on first run, so skipping
    microk8s_plugin_helm3_enable: false
    # false for virtualbox vm, where creating 'lo:microk8s' static IP will hang
    microk8s_plugin_host_access_enable: false
    # not a cluster
    microk8s_enabled_HA: false
    # configure this user's group, permissions, ~/.kube/config
    users: ['ubuntu']

  roles:
    # https://github.com/istvano/ansible_role_microk8s.git
    - role: ansible_role_microk8s
    - role: microk8s-get-kubeconfig
    - role: k9s
    #- role: kubernetes-dashboard
    #- role: istio-operator
