---

- hosts: microk8s
  gather_facts: yes
  become: yes

  vars:
    #istio_version: 1.7.5

  roles:
    # my debug web server
    - role: golang-hello-world-web

    # nginx deployment with ConfigMap content on ngnix ingress
    #- role: nginx-exposed
    # google sample hello app on nginx ingress
    #- role: hello-app-with-nginx-ingress
