# can deploy on single host by overriding HA variable, must use json syntax:
# ansible-playbook playbook_microk8s.yml --extra-vars '{"microk8s_enable_HA": false}
---

# roles run against cluster
- hosts: microk8s_HA
  gather_facts: yes
  become: yes
  vars:
    microk8s_enable_HA: true

  roles:
    # prerequisites and then main microk8s role
    - microk8s-prereq
    - ansible_role_microk8s
    # GUI utility for kubernetes
    - k9s

# additional roles for post-configuration, run just against single node
- hosts: microk8s
  gather_facts: no
  become: yes
  roles:
    - wait-for-microk8s
    # fetch kubeconfig locally for convenience
    - microk8s-get-kubeconfig-local

    # tiny-tools daemonset for troubleshooting
    - tiny-tools-all-nodes

    # configure additional IP to be used by MetalLB endpoints
    - additional-netplan-ip

    # create custom CA and cert for TLS
    # certs also slurped locally to /tmp
    - cert-with-ca
    # load secret into default namespace
    - { role: reapply-tls-secrets, tls_secret_overwrite: true }
