---

- hosts: microk8s
  gather_facts: yes
  become: yes

  vars:
    istio_version: 1.7.5

  roles:
    #- role: nginx-ingress
    - role: nginx-exposed
    #- role: hello-app-with-nginx-ingress

    #- role: istio-operator
    #- role: istio-gateway
