---

# ipaddr filter enabled in playbook_ansible_dependencies.yml
- name: find ip address1 for LB
  set_fact:
    metallb_ip1: "{{ additional_nic[0].netplan.addresses[0] | ipaddr('address') }}"
- debug: 
    msg: "going to use this bridged IP for a loadbalancer: {{metallb_ip1}}"

- name: find ip address2 for LB
  set_fact:
    metallb_ip2: "{{ additional_nic[1].netplan.addresses[0] | ipaddr('address') }}"
- debug: 
    msg: "going to use this bridged IP for a loadbalancer: {{metallb_ip2}}"

- name: Enable metallb with additional NIC addresses
  become: yes
  command: "microk8s enable metallb {{metallb_ip1}}-{{metallb_ip2}}"
  register: command_result
  changed_when: "'Addon metallb is already enabled' not in command_result.stdout"

# need to allow settling after enabling MetalLB
- pause:
    seconds: 15
  when: command_result.changed

- name: Wait for microk8s to be ready
  become: yes
  command: microk8s.status --wait-ready
  retries: 3
  delay: 15
