---

- name: check kubectl
  become: yes
  command: kubectl get nodes
  register: getnodes
- debug: msg="{{getnodes.stdout_lines}}"

- name: make sure cert pair exists
  stat:
    path: "{{item}}"
  register: cert_existence
  failed_when: not cert_existence.stat.exists
  loop:
    - "{{TMPDIR}}/{{ cert_domains_primary_ingress | first }}.crt"
    - "{{TMPDIR}}/{{ cert_domains_primary_ingress | first }}.key"

- name: make sure namespace exist
  command: kubectl create ns {{item}}
  register: result
  failed_when: not result.rc in [0,1]
  loop: [ 'default','nginx-ns','hello-app-ns','istio-system']

- name: delete tls secret when tls_secret_overwrite set to yes
  command: kubectl delete -n {{item}} secret tls-credential
  register: result
  failed_when: not result.rc in [0,1]
  loop: [ 'default','nginx-ns','hello-app-ns','istio-system']

- name: create tls secret
  command: kubectl create -n {{item}} secret tls tls-credential --key={{TMPDIR}}/{{ cert_domains_primary_ingress | first }}.key --cert={{TMPDIR}}/{{ cert_domains_primary_ingress | first }}.crt
  become: yes
  register: create_result
  loop: [ 'default','nginx-ns','hello-app-ns','istio-system']

- debug: msg="ok"
  loop: "{{create_result.results}}"
  loop_control:
    label: "{{item.stdout}}"
