---

- name: create kubectl config
  become: yes
  changed_when: true
  shell: microk8s config > ~/.kube/config
  args:
    executable: /bin/bash

- name: check kubectl
  become: yes
  command: kubectl get nodes
  register: getnodes
- debug: msg="{{getnodes.stdout_lines}}"

- name: get node count
  shell: kubectl get nodes | grep Ready | wc -l
  register: node_count
- debug: 
    msg: "total node count = {{node_count.stdout}}"

- name: copy tiny-tools yaml to remote host
  copy:
    src: tiny-tools.yaml
    dest: "{{TMPDIR}}/tiny-tools.yaml"
    force: true

- name: apply tiny-tools with single replica
  shell: kubectl apply -f {{TMPDIR}}/tiny-tools.yaml
  become: yes
  register: stdout
  retries: 3
  delay: 15
  until: stdout.rc == 0
- debug: msg="{{stdout.stdout_lines}}"

