---

- name: create kubectl config
  become: yes
  changed_when: true
  shell: microk8s config > ~/.kube/config
  args:
    executable: /bin/bash

- name: check kubectl
  become: yes
  command: kubectl get nodes
  register: getnodes
- debug: msg="{{getnodes.stdout_lines}}"

- name: create file out of every jinja2 templates
  template:
    src: "{{item}}"
    dest: "{{TMPDIR}}/{{ item | basename | regex_replace('.j2$', '') }}"
  with_fileglob: "../templates/*.j2"

- name: apply primary nginx deployment in nginx-ns namespace
  shell: kubectl apply -f {{TMPDIR}}/nginx.yaml
  become: yes
  register: stdout
- debug: msg="{{stdout.stdout_lines}}"

- name: apply primary nginx ingress in nginx-ns namespace
  shell: kubectl apply -f {{TMPDIR}}/nginx-on-nginx-ingress.yaml
  become: yes
  register: stdout
- debug: msg="{{stdout.stdout_lines}}"


- name: apply secondary nginx deployment in default namespace
  shell: kubectl apply -f {{TMPDIR}}/nginx-on-default-ns.yaml
  become: yes
  register: stdout
- debug: msg="{{stdout.stdout_lines}}"

- name: apply secondary nginx ingress in default namespace
  shell: kubectl apply -f {{TMPDIR}}/nginx-on-nginx-ingress-defaultns.yaml
  become: yes
  register: stdout
- debug: msg="{{stdout.stdout_lines}}"

- debug: msg="TODO do test pulls against these ingress points"

