---

- name: create kubectl config
  become: yes
  changed_when: true
  shell: microk8s config > ~/.kube/config
  args:
    executable: /bin/bash

- name: check kubectl
  become: yes
  command: kubectl get nodes
  register: getnodes
- debug: msg="{{getnodes.stdout_lines}}"

- name: create file out of every jinja2 templates
  template:
    src: "{{item}}"
    dest: "{{TMPDIR}}/{{ item | basename | regex_replace('.j2$', '') }}"
  with_fileglob: "../templates/*.j2"

- name: apply nginx deployment
  shell: kubectl apply -f {{TMPDIR}}/nginx.yaml
  become: yes
  register: stdout
- debug: msg="{{stdout.stdout_lines}}"

- name: apply nginx virtualservice
  shell: kubectl apply -f {{TMPDIR}}/nginx-on-nginx-ingress.yaml.j2
  become: yes
  register: stdout
- debug: msg="{{stdout.stdout_lines}}"

