---
# dependency on: ansible-galaxy collection install community.crypto
# needs PyOpenSSL or cryptogrphy
#
# set to force:no so that once a key/cert pair is created, we don't overwrite

#
# Create CA 
# https://milliams.com/posts/2020/ansible-certificate-authority/
#
- name: create CA key
  community.crypto.openssl_privatekey:
    path: "{{TMPDIR}}/myCA.key"
    force: "{{cert_overwrite}}"
  register: ca_key

- name: create the CA CSR
  community.crypto.openssl_csr:
    path: "{{TMPDIR}}/myCA.csr"
    privatekey_path: "{{ ca_key.filename }}"
    common_name: "myCA"
    force: "{{cert_overwrite}}"
  register: ca_csr

- name: sign the CA CSR
  openssl_certificate:
    path: "{{TMPDIR}}/myCA.crt"
    csr_path: "{{ ca_csr.filename }}"
    privatekey_path: "{{ ca_key.filename }}"
    provider: selfsigned
    force: "{{cert_overwrite}}"
  register: ca_crt

- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  community.crypto.openssl_privatekey:
    path: "{{TMPDIR}}/{{cert_domains_primary_ingress | first}}.key"
    force: "{{cert_overwrite}}"
  register: cert_key

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: "{{TMPDIR}}/{{cert_domains_primary_ingress | first}}.csr"
    privatekey_path: "{{TMPDIR}}/{{cert_domains_primary_ingress | first}}.key"
    key_usage:
      - digitalSignature
      - keyAgreement
    extended_key_usage:
      - clientAuth
    common_name: "{{ cert_domains_primary_ingress | first }}"
    subject_alt_name: "{{ item.value | map('regex_replace', '^', 'DNS:') | list }}"
    force: "{{cert_overwrite}}"
  register: cert_csr
  with_dict:
    dns_server: "{{ cert_domains_primary_ingress + cert_domains_secondary_ingress }}"

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: "{{TMPDIR}}/{{ cert_domains_primary_ingress | first }}.crt"
    privatekey_path: "{{TMPDIR}}/{{cert_domains_primary_ingress|first}}.key"
    csr_path: "{{TMPDIR}}/{{cert_domains_primary_ingress|first}}.csr"
    ownca_path: "{{ca_crt.filename}}"
    ownca_privatekey_path: "{{ca_key.filename}}"
    provider: ownca # selfsigned if this had been self-signed
    force: "{{cert_overwrite}}"
  register: cert_crt

- name: generate pkcs12 file
  community.crypto.openssl_pkcs12:
    action: export
    path: "{{TMPDIR}}/{{ cert_domains_primary_ingress | first }}.p12"
    friendly_name: "{{ cert_domains_primary_ingress | first }}"
    privatekey_path: "{{ cert_key.filename }}"
    certificate_path: "{{ cert_crt.filename }}"
    # was called 'ca_cerficates' before 2.8
    other_certificates: "{{ ca_crt.filename }}"
    force: "{{cert_overwrite}}"
    state: present
  register: cert_p12

- name: show cert
  community.crypto.x509_certificate_info:
    path: "{{cert_crt.filename}}"
  register: cert_result
- debug: 
    msg: >
      subject: {{cert_result.subject}}
      issuer: {{cert_result.issuer}}
      subject_alt_name: {{cert_result.subject_alt_name}}
