---

- name: create kubectl config
  become: yes
  changed_when: true
  shell: microk8s config > ~/.kube/config
  args:
    executable: /bin/bash

- name: check kubectl
  become: yes
  command: kubectl get nodes
  register: getnodes
- debug: msg="{{getnodes.stdout_lines}}"

- name: create file out of every jinja2 templates
  template:
    src: "{{item}}"
    dest: "{{TMPDIR}}/{{ item | basename | regex_replace('.j2$', '') }}"
  with_fileglob: "../templates/*.j2"

- name: apply hello-app v1
  shell: kubectl apply -f {{TMPDIR}}/hello-app-v1.yaml
  become: yes
  register: stdout
- debug: msg="{{stdout.stdout_lines}}"

- name: apply nginx ingress for hello-app v1
  shell: kubectl apply -f {{TMPDIR}}/hello-app-v1-on-nginx-ingress.yaml
  become: yes
  register: stdout
- debug: msg="{{stdout.stdout_lines}}"

- name: kubectl to get hello-app-v1-service URL
  command: |
    kubectl get service hello-app-v1-service -n hello-app-ns --output jsonpath='http://{.spec.clusterIP}:{.spec.ports[?(@.name=="http")].port}'
  register: url_from_service
- debug: msg="{{url_from_service.stdout}}"

- name: test pull from hello-app-v1-service
  uri:
    url: "{{url_from_service.stdout}}"
    method: GET
    return_content: true
  register: pull_result
- debug: msg="{{pull_result.content}}"



- name: kubectl to get insecure nginx ingress controller service URL
  command: |
    kubectl get service ingress-nginx-controller -n ingress-nginx --output jsonpath='http://{.spec.clusterIP}:{.spec.ports[?(@.name=="http")].port}'
  register: http_ingress
- debug: msg="{{http_ingress.stdout}}"
- name: kubectl to get secure nginx ingress controller service URL
  command: |
    kubectl get service ingress-nginx-controller -n ingress-nginx --output jsonpath='https://{.spec.clusterIP}:{.spec.ports[?(@.name=="https")].port}'
  register: https_ingress
- debug: msg="{{https_ingress.stdout}}"

- name: test pull from secure nginx ingress
  uri:
    url: "{{https_ingress.stdout}}"
    method: GET
    return_content: true
    validate_certs: false
    headers:
      Host: "{{ cert_domains_primary_ingress | first }}"
  register: pull_result
- debug: msg="{{pull_result.content}}"

#- name: test cert and CA using openssl
#  shell: echo | openssl s_client -showcerts -servername microk8s-1.local -connect 10.152.183.204:443 -CAfile /tmp/myCA.local.crt

